version: "3.4"
services:
  data-workspace:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: data-workspace
    ports:
      - "8000:8000"
    env_file: .envs/dev.env
    links:
      - "data-workspace-postgres"
      - "data-workspace-redis"
    volumes:
      - ./dataworkspace:/dataworkspace
  data-workspace-celery:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: data-workspace
    env_file: .envs/dev.env
    links:
      - "data-workspace-postgres"
      - "data-workspace-redis"
    command: "/dataworkspace/start-celery-dev.sh"
    volumes:
      - ./dataworkspace:/dataworkspace
      - db-logs-dev:/var/log/postgres
  data-workspace-postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    image: data-workspace-postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data-dev:/var/lib/postgresql/data
      - db-logs-dev:/var/log/postgres
  data-workspace-redis:
    build:
      context: redis
      dockerfile: Dockerfile
    image: data-workspace-redis
    ports:
      - "6379:6379"


volumes:
  db-data-dev:
  db-logs-dev:
  
networks:
  default:
    external:
      name: data-infrastructure-shared-network
