version: "3"
services:
  data-workspace-test:
    build:
      context: .
      dockerfile: Dockerfile-test
    image: data-workspace-test
    env_file:
      - ./.envs/test.env
    ports:
      - "8000:8000"
    links:
      - "data-workspace-postgres"
      - "data-workspace-redis"
    extra_hosts:
      - "localapps.com:127.0.0.1"
      - "testapplication-23b40dd9.localapps.com:127.0.0.1"
  data-workspace-postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    image: data-workspace-postgres
    ports:
      - "5432:5432"
  data-workspace-redis:
    build:
      context: redis
      dockerfile: Dockerfile
    image: data-workspace-redis
    ports:
      - "6379:6379"
