version: "3"
services:
  analysis-workspace:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    links:
      - "analysis-workspace-postgres"
      - "analysis-workspace-redis"
  analysis-workspace-postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
  analysis-workspace-redis:
    build:
      context: .
      dockerfile: Dockerfile-redis
    ports:
      - "6379:6379"
