version: "3"

services:
  data-workspace:
    build:
      context: .
      dockerfile: Dockerfile
    image: data-workspace
    ports:
      - "8000:8000"
    env_file: .envs/dev.env
    links:
      - "data-workspace-postgres"
      - "data-workspace-redis"
      - "data-workspace-metabase"

  data-workspace-postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    image: data-workspace-postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  data-workspace-redis:
    build:
      context: redis
      dockerfile: Dockerfile
    image: data-workspace-redis
    ports:
      - "6379:6379"

  data-workspace-metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"

volumes:
  db-data:
