version: 2
jobs:
  build:
    docker:
      # Test and code run in _other_ docker containers, so mostly doesn't matter
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            touch .env
            make docker-test
      - run:
          name: Install requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
      - run:
          name: Run static checks
          command: |
            . venv/bin/activate
            make check
