version: 2

jobs:
  docker-test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run test
          command: |
            touch .envs/dev.env
            make docker-test
  check-linting:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
      - run:
          name: Run static checks
          command: |
            . venv/bin/activate
            make check

workflows:
  version: 2
  build:
    jobs:
      - docker-test
      - check-linting
